### ISSUE TITLE
On the first load Web is slowly !!!

### ISSUE THREAD

**Issue by 22p21s0045** [Hello-Goose/Hello-Goose#20]
I think image file is very big it use png file I recommend to compress file before use it is so slow on first loading but now  I try to fix about this performance by use Imgbot but I try  it for 1 hour  but it not work LOL have another one have solution yet 
Performance Score:
https://pagespeed.web.dev/analysis/https-hello-goose-frt5npo4c-xsmitylnwzas-projects-vercel-app/htvkyfbqfc?form_factor=desktop

Feel free  😂

**Comment by Sitthata** [comment]
Thank you for pointing it out. I've already tried compressing various images on our website, but I've focused only on the crucial and large-sized ones, there are still some possible issues because some images can't be compressed. As you can see, despite these limitations, the performance of the website has improved by around 20%. Hope this help!
![image](https://github.com/Hello-Goose/Hello-Goose/assets/106243338/f8682c47-e6e8-4564-8485-2811ca8d177f)
